import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import SiteLogo from '../components/icons/SiteLogo'
import Button from '../components/Button'
import styled from 'styled-components'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <div style={{display: 'flex', alignItems: 'center', fontSize: '30px'}}>
        <SiteLogo />
        <h2>Logo</h2>
        </div>
        <Button />
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Main
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Foorter
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
